### ISSUE TITLE
Problem with Findbugs of SonarQube-5.6.6 version.

### ISSUE THREAD

**Issue by mohanss08** [SonarQubeCommunity/sonar-findbugs#103]
Dear Team,

I have problem with Findbugs of SonarQube-5.6.6 version.

Our Environment details as follows:

SonarQube Server Version - 5.6.6-(LTS) (64-Bit). 
Java Plugin Version – sonar-java-plugin-4.9.0.9858.jar
Find Bugs Plugin Version - sonar-findbugs-plugin-3.4.4.jar
SonarRunner Version - sonar-runner-2.4
Sonar Build Machine – Ubuntu 16.04.2 LTS (64-Bit)
Source Scanning Mode - Jenkins
Source Code Language - Java

Problem Description:

With the above configurations, We are facing problem with source code scanning through Jenkins. We have configured version control tool to download the source code, then we have configured only Sonar-Runner to scan the source. 

Note: No build configured, So it does not compile the source.

With only source code scanning, We are getting below errors through jenkins.
```
9:36:37.702 WARN  - Findbugs needs sources to be compiled. Please build project before executing sonar or check the location of compiled classes to make it possible for Findbugs to analyse your project.
INFO: ------------------------------------------------------------------------
INFO: EXECUTION FAILURE
INFO: ------------------------------------------------------------------------
Total time: 1:18.217s
Final Memory: 18M/360M
INFO: ------------------------------------------------------------------------
ERROR: Error during Sonar runner execution
org.sonar.runner.impl.RunnerException: Unable to execute Sonar
	at org.sonar.runner.impl.BatchLauncher$1.delegateExecution(BatchLauncher.java:91)
	at org.sonar.runner.impl.BatchLauncher$1.run(BatchLauncher.java:75)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.sonar.runner.impl.BatchLauncher.doExecute(BatchLauncher.java:69)
	at org.sonar.runner.impl.BatchLauncher.execute(BatchLauncher.java:50)
	at org.sonar.runner.api.EmbeddedRunner.doExecute(EmbeddedRunner.java:102)
	at org.sonar.runner.api.Runner.execute(Runner.java:100)
	at org.sonar.runner.Main.executeTask(Main.java:70)
	at org.sonar.runner.Main.execute(Main.java:59)
	at org.sonar.runner.Main.main(Main.java:53)
Caused by: java.lang.IllegalStateException: Can not execute Findbugs
	at org.sonar.plugins.findbugs.FindbugsExecutor.execute(FindbugsExecutor.java:169)
	at org.sonar.plugins.findbugs.FindbugsSensor.execute(FindbugsSensor.java:88)
	at org.sonar.batch.sensor.SensorWrapper.analyse(SensorWrapper.java:57)
	at org.sonar.batch.phases.SensorsExecutor.executeSensor(SensorsExecutor.java:58)
	at org.sonar.batch.phases.SensorsExecutor.execute(SensorsExecutor.java:50)
	at org.sonar.batch.phases.AbstractPhaseExecutor.execute(AbstractPhaseExecutor.java:83)
	at org.sonar.batch.scan.ModuleScanContainer.doAfterStart(ModuleScanContainer.java:192)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:142)
	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:127)
	at org.sonar.batch.scan.ProjectScanContainer.scan(ProjectScanContainer.java:241)
	at org.sonar.batch.scan.ProjectScanContainer.scanRecursively(ProjectScanContainer.java:236)
	at org.sonar.batch.scan.ProjectScanContainer.doAfterStart(ProjectScanContainer.java:226)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:142)
	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:127)
	at org.sonar.batch.task.ScanTask.execute(ScanTask.java:47)
	at org.sonar.batch.task.TaskContainer.doAfterStart(TaskContainer.java:86)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:142)
	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:127)
	at org.sonar.batch.bootstrap.GlobalContainer.executeTask(GlobalContainer.java:106)
	at org.sonar.batch.bootstrapper.Batch.executeTask(Batch.java:119)
	at org.sonar.batch.bootstrapper.Batch.execute(Batch.java:79)
	at org.sonar.runner.batch.IsolatedLauncher.execute(IsolatedLauncher.java:48)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.sonar.runner.impl.BatchLauncher$1.delegateExecution(BatchLauncher.java:87)
	... 9 more
Caused by: java.lang.IllegalStateException: This project contains Java source files that are not compiled.
	at org.sonar.plugins.findbugs.FindbugsConfiguration.getFindbugsProject(FindbugsConfiguration.java:120)
	at org.sonar.plugins.findbugs.FindbugsExecutor.execute(FindbugsExecutor.java:119)
	... 35 more
Build step 'Execute shell' marked build as failure
```

Note: I have tried with sonar-findbugs-plugin-3.4.3 version as well, But same problem, Also we don’t have target/classes folders, As the we have committed only our source files under version control tool. Hence I can’t configure - sonar.java.binaries=/target/classes. In my sonar-project.properties file, So kindly advise me to fix the same.

Rgds,
Mohan

**Comment by mohanss08** [comment]
Even after creating target/classes folders and added the sonar.java.binaries=target/classes
in my sonar-project.properties file. tried the scanning again, But it failed with same error.

**Comment by candicelinyi** [comment]
You can add "Execute Shell" in Jenkins job before Sonar, and run test there, like putting "mvn test", "gradle test" in "Excecute Shell", then system will compile your project and generate classes in target/classes folders, so that Sonar can find the classes.

**Comment by mohanss08** [comment]
True, But we don't want to build our source, Just wanted to perform only sonar scanning through sonar runner.

**Comment by mohanss08** [comment]
Hi Team,

So build is mandatory to use findbug plugin version-3.4.4 in my Sonarqube version-5.6.6-LTS?
Kindly advise me.
-Mohan

**Comment by mohanss08** [comment]
Team, Any support on this issue would be highly appreciated.

**Comment by h3xstream** [comment]
```
True, But we don't want to build our source, Just wanted to perform only sonar scanning through sonar runner.
```
This is mandatory.

**Comment by pgodithi** [comment]
Hey I am using oracle java 10 and using sonar for code analysis, getting the following error, can anyone tell me the solution for this.
sonarqube version: 6.7.3
find bugs plugin: 3.7.0

at edu.umd.cs.findbugs.FindBugs2.execute(FindBugs2.java:275)
at org.sonar.plugins.findbugs.FindbugsExecutor$FindbugsTask.call(FindbugsExecutor.java:235)

Caused by: java.lang.IllegalStateException: Can not execute Findbugs

**Comment by mohanss08** [comment]
Oracle java supported for Sonarqube is up to 7 only. You need to downgrade
your java version.

Refer the following link for supported platforms.

https://docs.sonarqube.org/plugins/servlet/mobile?contentId=11634463#content/view/11634463
