### ISSUE TITLE
FindBugs Plugin incompatible with Sonar 6.3 and 6.4

### ISSUE THREAD

**Issue by jancur** [SonarQubeCommunity/sonar-findbugs#115]
After upgrading to Sonar 6.3.1 from 6.3 the FindBugs plugin is no longer listed as available.
Upgraded to Sonar 6.4.
The FindBugs plugin is still not available in Sonar 6.4.

Sonarqube plugin version matrix also shows FIndBugs as being incompatible with 6.3 and 6.4,
https://docs.sonarqube.org/display/PLUG/Plugin+Version+Matrix

When can we expect FindBugs to be available again?

**Comment by kzaikin** [comment]
I have a Sonar 6.4 working with Findbugs plugin just fine

**Comment by jancur** [comment]
@kzaikin Are you using plugin version 3.4.4 or 3.5.0 with Sonar 6.4? Did you manually install the plugin or use the Sonar update center? Thanks.

**Comment by tiendungitd** [comment]
same question, which version plugin are you using?

**Comment by ricktg** [comment]
go the same issue

**Comment by Omertron** [comment]
I have just updated my sonar installation too, from 6.3 to 6.4 (build 25310)
I had to disable (remove) "sonar-findbugs-plugin-3.4.4.jar" for sonar to start otherwise it throws this stack trace in the ```web.log```

````
2017.06.21 15:01:48 ERROR web[][o.s.s.p.Platform] Background initialization failed. Stopping SonarQube
java.lang.IllegalStateException: Fail to load plugin Findbugs [findbugs]
        at org.sonar.server.plugins.ServerExtensionInstaller.installExtensions(ServerExtensionInstaller.java:73)
        at org.sonar.server.platform.platformlevel.PlatformLevel4.start(PlatformLevel4.java:534)
        at org.sonar.server.platform.Platform.start(Platform.java:231)
        at org.sonar.server.platform.Platform.startLevel34Containers(Platform.java:205)
        at org.sonar.server.platform.Platform.access$500(Platform.java:46)
        at org.sonar.server.platform.Platform$1.lambda$doRun$0(Platform.java:119)
        at org.sonar.server.platform.Platform$AutoStarterRunnable.runIfNotAborted(Platform.java:391)
        at org.sonar.server.platform.Platform$1.doRun(Platform.java:119)
        at org.sonar.server.platform.Platform$AutoStarterRunnable.run(Platform.java:375)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NoClassDefFoundError: org/sonar/api/web/CodeColorizerFormat
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
        at org.sonar.classloader.ClassRealm.loadClassFromSelf(ClassRealm.java:125)
        at org.sonar.classloader.ParentFirstStrategy.loadClass(ParentFirstStrategy.java:37)
        at org.sonar.classloader.ClassRealm.loadClass(ClassRealm.java:87)
        at org.sonar.classloader.ClassRealm.loadClass(ClassRealm.java:76)
        at org.sonar.plugins.findbugs.FindbugsPlugin.define(FindbugsPlugin.java:43)
        at org.sonar.server.plugins.ServerExtensionInstaller.installExtensions(ServerExtensionInstaller.java:63)
        ... 9 common frames omitted
Caused by: java.lang.ClassNotFoundException: org.sonar.api.web.CodeColorizerFormat
        at org.sonar.classloader.ParentFirstStrategy.loadClass(ParentFirstStrategy.java:39)
        at org.sonar.classloader.ClassRealm.loadClass(ClassRealm.java:87)
        at org.sonar.classloader.ClassRealm.loadClass(ClassRealm.java:76)
        ... 24 common frames omitted
2017.06.21 15:01:48 INFO  web[][o.s.p.StopWatcher] Stopping process
````

**Comment by Omertron** [comment]
Manually upgrading to 3.5.0 of findbugs allows me to restart sonar (albeit with some issues in the console display of the version number), but without manual installation findbugs is not available to me in sonar.

**Comment by h3xstream** [comment]
The plugin will release soon on the update center.
https://groups.google.com/forum/#!topic/sonarqube/xro9ZAtZdxI
