### ISSUE TITLE
Analysis with 3.4.1 fails for modules with only testclasses

### ISSUE THREAD

**Issue by amandel** [SonarQubeCommunity/sonar-findbugs#33]
I've a maven multi module maven project with a special xxx-test module that only contains test java sources. These are compiled and class files are available in `target/test-classes`, but there is no `target/classes` directory. While the analysis worked fine with SQ 5.6 and version 3.3 of the sonar-findbugs-plugin it fails with version 3.4.1-fix of the plugin giving: "No files to analyze could be opened"

```
Failed to execute goal org.sonarsource.scanner.maven:sonar-maven-plugin:3.0.2:sonar (default-cli) on project xxx-parent: Can not execute Findbugs: java.lang.RuntimeException: java.io.IOException: No files to analyze could be opened -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.sonarsource.scanner.maven:sonar-maven-plugin:3.0.2:sonar (default-cli) on project tbes-parent: Can not execute Findbugs
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:216)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:120)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:355)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:155)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:584)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:216)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:160)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoExecutionException: Can not execute Findbugs
	at org.sonarsource.scanner.maven.bootstrap.ExceptionHandling.handle(ExceptionHandling.java:36)
	at org.sonarsource.scanner.maven.bootstrap.ScannerBootstrapper.execute(ScannerBootstrapper.java:81)
	at org.sonarsource.scanner.maven.SonarQubeMojo.execute(SonarQubeMojo.java:112)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:132)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	... 19 more
Caused by: java.lang.IllegalStateException: Can not execute Findbugs
	at org.sonar.plugins.findbugs.FindbugsExecutor.execute(FindbugsExecutor.java:166)
	at org.sonar.plugins.findbugs.FindbugsSensor.execute(FindbugsSensor.java:88)
	at org.sonar.batch.sensor.SensorWrapper.analyse(SensorWrapper.java:57)
	at org.sonar.batch.phases.SensorsExecutor.executeSensor(SensorsExecutor.java:58)
	at org.sonar.batch.phases.SensorsExecutor.execute(SensorsExecutor.java:50)
	at org.sonar.batch.phases.AbstractPhaseExecutor.execute(AbstractPhaseExecutor.java:83)
	at org.sonar.batch.scan.ModuleScanContainer.doAfterStart(ModuleScanContainer.java:192)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:142)
	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:127)
	at org.sonar.batch.scan.ProjectScanContainer.scan(ProjectScanContainer.java:241)
	at org.sonar.batch.scan.ProjectScanContainer.scanRecursively(ProjectScanContainer.java:236)
	at org.sonar.batch.scan.ProjectScanContainer.scanRecursively(ProjectScanContainer.java:234)
	at org.sonar.batch.scan.ProjectScanContainer.doAfterStart(ProjectScanContainer.java:226)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:142)
	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:127)
	at org.sonar.batch.task.ScanTask.execute(ScanTask.java:47)
	at org.sonar.batch.task.TaskContainer.doAfterStart(TaskContainer.java:86)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:142)
	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:127)
	at org.sonar.batch.bootstrap.GlobalContainer.executeTask(GlobalContainer.java:106)
	at org.sonar.batch.bootstrapper.Batch.executeTask(Batch.java:119)
	at org.sonarsource.scanner.api.internal.batch.BatchIsolatedLauncher.execute(BatchIsolatedLauncher.java:62)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.sonarsource.scanner.api.internal.IsolatedLauncherProxy.invoke(IsolatedLauncherProxy.java:60)
	at com.sun.proxy.$Proxy21.execute(Unknown Source)
	at org.sonarsource.scanner.api.EmbeddedScanner.doExecute(EmbeddedScanner.java:240)
	at org.sonarsource.scanner.api.EmbeddedScanner.runAnalysis(EmbeddedScanner.java:151)
	at org.sonarsource.scanner.maven.bootstrap.ScannerBootstrapper.execute(ScannerBootstrapper.java:78)
	... 22 more
Caused by: java.util.concurrent.ExecutionException: java.lang.RuntimeException: java.io.IOException: No files to analyze could be opened
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:206)
	at org.sonar.plugins.findbugs.FindbugsExecutor.execute(FindbugsExecutor.java:158)
	... 52 more
Caused by: java.lang.RuntimeException: java.io.IOException: No files to analyze could be opened
	at com.google.common.base.Throwables.propagate(Throwables.java:156)
	at org.sonar.plugins.findbugs.FindbugsExecutor$FindbugsTask.call(FindbugsExecutor.java:216)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.IOException: No files to analyze could be opened
	at edu.umd.cs.findbugs.FindBugs2.execute(FindBugs2.java:276)
	at org.sonar.plugins.findbugs.FindbugsExecutor$FindbugsTask.call(FindbugsExecutor.java:213)
	... 4 more
```

**Comment by amandel** [comment]
Thanks for picking this up. And I'm sure you saw that this is a regression coming from 3.3.

As a different workaround you can also skip the module in SonarQube altogether using maven means by adding `-pl !xxx-test` (`xxx-test` being the module name) to your `mvn sonar:sonar call`. This helps if you can not modify the project under analysis but you will obviously get no results at all for the excluded module.

I'm not sure if it is feasible through the Sonarqube API. Generally I would prefer to get a (blocker) issue reported sth like "Could not execute Findbugs cause of generic issue...", rather than a completely broken analysis in case of such a fatal analyzer issue. Might be I should ask for this on the other side of the API.

**Comment by h3xstream** [comment]
Currently, I was doing logging with WARN marker for non-critical observation.
Such as _having JSPs that are not precompiled_ or _compiled class that do not have java file associated_.

You could grep for those specific messages on your CI build task.

**Comment by amandel** [comment]
IMHO it would be nice to see these as issues in SonarQube: "Java file was not analyzed by FindBugs because no corresponding class file was found." or "..source could not be parsed", "...encoding issues in the source file." ...

**Comment by h3xstream** [comment]
@amandel Good point. I could not found anything like it in the API. It would be good feature request.

**Comment by h3xstream** [comment]
I reconsider this issue as a blocker for the 3.4 release.

You can find the latest package here (sonar-findbugs-3.4.3.jar) : https://github.com/SonarQubeCommunity/sonar-findbugs/releases/tag/3.4

It is a minor code change (2 ifs conditions added only) but it should save a couple of headaches for users.

**Comment by amandel** [comment]
Cool! I can confirm that 3.4.3 fixes the above issue.

```
[INFO] Sensor FindBugs Sensor
[WARNING] Findbugs needs sources to be compiled. Please build project before executing sonar or check the location of compiled classes to make it possible for Findbugs to analyse your project.
[INFO] Findbugs analysis skipped for this project.
[INFO] Sensor FindBugs Sensor (done) | time=19ms
```

Thanks!

**Comment by h3xstream** [comment]
@amandel Thanks for the quick feedback.
