### ISSUE TITLE
NPE in ByteCodeResourceLocator  during code analysis 

### ISSUE THREAD

**Issue by mhankus** [SonarQubeCommunity/sonar-findbugs#38]
During code analysis my maven job fails with stacktrace shown below.  I'm trying to find root cause - if you have some tips how to dig deeper please let me know.  

```
02:22:00 [ERROR] Failed to execute goal org.sonarsource.scanner.maven:sonar-maven-plugin:3.0.2:sonar (default-cli) on project netpr-aggregator: null: MojoExecutionException: NullPointerException -> [Help 1]
02:22:00 org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.sonarsource.scanner.maven:sonar-maven-plugin:3.0.2:sonar (default-cli) on project netpr-aggregator: null
02:22:00    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
02:22:00    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
02:22:00    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
02:22:00    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
02:22:00    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
02:22:00    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
02:22:00    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
02:22:00    at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
02:22:00    at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
02:22:00    at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
02:22:00    at org.jvnet.hudson.maven3.launcher.Maven32Launcher.main(Maven32Launcher.java:132)
02:22:00    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
02:22:00    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
02:22:00    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
02:22:00    at java.lang.reflect.Method.invoke(Method.java:498)
02:22:00    at org.codehaus.plexus.classworlds.launcher.Launcher.launchStandard(Launcher.java:330)
02:22:00    at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:238)
02:22:00    at jenkins.maven3.agent.Maven32Main.launch(Maven32Main.java:186)
02:22:00    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
02:22:00    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
02:22:00    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
02:22:00    at java.lang.reflect.Method.invoke(Method.java:498)
02:22:00    at hudson.maven.Maven3Builder.call(Maven3Builder.java:136)
02:22:00    at hudson.maven.Maven3Builder.call(Maven3Builder.java:71)
02:22:00    at hudson.remoting.UserRequest.perform(UserRequest.java:153)
02:22:00    at hudson.remoting.UserRequest.perform(UserRequest.java:50)
02:22:00    at hudson.remoting.Request$2.run(Request.java:332)
02:22:00    at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:68)
02:22:00    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
02:22:00    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
02:22:00    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
02:22:00    at java.lang.Thread.run(Thread.java:745)
02:22:00 Caused by: org.apache.maven.plugin.MojoExecutionException
02:22:00    at org.sonarsource.scanner.maven.bootstrap.ExceptionHandling.handle(ExceptionHandling.java:36)
02:22:00    at org.sonarsource.scanner.maven.bootstrap.ScannerBootstrapper.execute(ScannerBootstrapper.java:81)
02:22:00    at org.sonarsource.scanner.maven.SonarQubeMojo.execute(SonarQubeMojo.java:112)
02:22:00    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
02:22:00    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
02:22:00    ... 31 more
02:22:00 Caused by: java.lang.NullPointerException
02:22:00    at org.sonar.plugins.findbugs.resource.ByteCodeResourceLocator.getJspLineNumberFromSmap(ByteCodeResourceLocator.java:175)
02:22:00    at org.sonar.plugins.findbugs.resource.ByteCodeResourceLocator.findJspLine(ByteCodeResourceLocator.java:142)
02:22:00    at org.sonar.plugins.findbugs.FindbugsSensor.execute(FindbugsSensor.java:127)
02:22:00    at org.sonar.batch.sensor.SensorWrapper.analyse(SensorWrapper.java:57)
02:22:00    at org.sonar.batch.phases.SensorsExecutor.executeSensor(SensorsExecutor.java:58)
02:22:00    at org.sonar.batch.phases.SensorsExecutor.execute(SensorsExecutor.java:50)
02:22:00    at org.sonar.batch.phases.AbstractPhaseExecutor.execute(AbstractPhaseExecutor.java:83)
02:22:00    at org.sonar.batch.scan.ModuleScanContainer.doAfterStart(ModuleScanContainer.java:192)
02:22:00    at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:142)
02:22:00    at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:127)
02:22:00    at org.sonar.batch.scan.ProjectScanContainer.scan(ProjectScanContainer.java:241)
02:22:00    at org.sonar.batch.scan.ProjectScanContainer.scanRecursively(ProjectScanContainer.java:236)
02:22:00    at org.sonar.batch.scan.ProjectScanContainer.scanRecursively(ProjectScanContainer.java:234)
02:22:00    at org.sonar.batch.scan.ProjectScanContainer.doAfterStart(ProjectScanContainer.java:226)
02:22:00    at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:142)
02:22:00    at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:127)
02:22:00    at org.sonar.batch.task.ScanTask.execute(ScanTask.java:47)
02:22:00    at org.sonar.batch.task.TaskContainer.doAfterStart(TaskContainer.java:86)
02:22:00    at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:142)
02:22:00    at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:127)
02:22:00    at org.sonar.batch.bootstrap.GlobalContainer.executeTask(GlobalContainer.java:106)
02:22:00    at org.sonar.batch.bootstrapper.Batch.executeTask(Batch.java:119)
02:22:00    at org.sonarsource.scanner.api.internal.batch.BatchIsolatedLauncher.execute(BatchIsolatedLauncher.java:62)
02:22:00    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
02:22:00    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
02:22:00    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
02:22:00    at java.lang.reflect.Method.invoke(Method.java:498)
02:22:00    at org.sonarsource.scanner.api.internal.IsolatedLauncherProxy.invoke(IsolatedLauncherProxy.java:60)
02:22:00    at com.sun.proxy.$Proxy131.execute(Unknown Source)
02:22:00    at org.sonarsource.scanner.api.EmbeddedScanner.doExecute(EmbeddedScanner.java:240)
02:22:00    at org.sonarsource.scanner.api.EmbeddedScanner.runAnalysis(EmbeddedScanner.java:151)
02:22:00    at org.sonarsource.scanner.maven.bootstrap.ScannerBootstrapper.execute(ScannerBootstrapper.java:78)
02:22:00    ... 34 more

```

**Comment by h3xstream** [comment]
I found that the NPE will occurs if a bug is report and the class can't be mapped to its original files.

I am going to fix 2 others bug soon. I will provided you a version with more verbose error.

I would like to know two details :
 - What JSP compiler you are using in your build?
 - Where are place the compiled classes? (tip: search for classes files with "jsp" in the filename)

**Comment by mhankus** [comment]
My project is contains multiple modules. 
```
 find . -name "jsp"
./module1/src/main/webapp/WEB-INF/jsp
./module1/target/admin/WEB-INF/jsp
./module2/src/main/java/pl/netpr/module2/jsp
./module2/src/main/webapp/WEB-INF/jsp
./module2/target/ROOT/WEB-INF/jsp
./module2/target/ROOT/WEB-INF/classes/pl/netpr/module2/jsp
./module2/target/ROOT/WEB-INF/classes/jsp
./module2/target/ROOT/WEB-INF/classes/jsp/WEB_002dINF/jsp
./module2/target/classes/pl/netpr/module2/jsp
./module2/target/classes/jsp
./module2/target/classes/jsp/WEB_002dINF/jsp
./module2/target/jsp-source/jsp
./module2/target/jsp-source/jsp/WEB_002dINF/jsp
./module3/target/ROOT/WEB-INF/classes/jsp
./module3/target/classes/jsp
./module3/target/jsp-source/jsp
```
Classes for jsp files are located in (module2 example, only index.jsp - there are 2 index.jsp files one in webapp root and seconf in WEB-INF)
```
./module2/target/ROOT/WEB-INF/classes/jsp/index_jsp.class
./module2/target/ROOT/WEB-INF/classes/jsp/WEB_002dINF/jsp/index_jsp.class
./module2/target/classes/jsp/index_jsp.class
./module2/target/classes/jsp/WEB_002dINF/jsp/index_jsp.class
./module2/target/jsp-source/jsp/index_jsp.class
./module2/target/jsp-source/jsp/WEB_002dINF/jsp/index_jsp.class
```
I must take a loook at my pom.xml, it is big and old, maybe there is misconfiguration. 
For compilation I use 
```
<groupId>org.jasig.mojo.jspc</groupId>
<artifactId>jspc-compiler-tomcat8</artifactId>
<version>2.0.2</version>
```

**Comment by h3xstream** [comment]
I will be doing some tests with this maven plugin. Thanks for the infos. I got all I need to reproduce.

**Comment by h3xstream** [comment]
@mhankus 
I cannot make the plugin work. I was only able to find [this documentation](https://tomcat.apache.org/tomcat-8.0-doc/jasper-howto.html).

This is the configuration I have tried:
```xml
            <build>
                <plugins>
                    <plugin>
                        <groupId>org.jasig.mojo.jspc</groupId>
                        <artifactId>jspc-compiler-tomcat8</artifactId>
                        <version>2.0.2</version>
                        <executions>
                            <execution>
                                <id>jspc</id>
                                <goals>
                                    <goal>jspc</goal>
                                </goals>
                                <configuration>
                                    <suppressSmap>false</suppressSmap>
                                </configuration>
                            </execution>
                        </executions>
                    </plugin>
                </plugins>
            </build>
```

**Comment by h3xstream** [comment]
[Got it!](http://developer.jasig.org/projects/jspc-maven-plugin/2.0.0/jspc-maven-plugin/usage.html)
```xml
            <build>
                <plugins>
                    <plugin>
                        <groupId>org.jasig.mojo.jspc</groupId>
                        <artifactId>jspc-maven-plugin</artifactId>
                        <executions>
                            <execution>
                                <goals>
                                    <goal>compile</goal>
                                </goals>
                            </execution>
                        </executions>

                        <!-- Use the Tomcat 8 JSP compiler -->
                        <dependencies>
                            <dependency>
                                <groupId>org.jasig.mojo.jspc</groupId>
                                <artifactId>jspc-compiler-tomcat8</artifactId>
                                <version>2.0.2</version>
                            </dependency>
                        </dependencies>
                    </plugin>
                </plugins>
            </build>
```

**Comment by h3xstream** [comment]
So far I was able to recompile this demo project with tomcat8 plugin: https://github.com/find-sec-bugs/find-sec-bugs-demos/tree/master/java-web-jsp

**Comment by h3xstream** [comment]
I will start a beta phase for a new release that include a couple of fixes.
The last fix to include is this NPE.

Unfortunetly, I am not able to reproduce the problem by combining the tomcat8 plugin and the test projects I have. I have create a alpha release of the plugin that should give more detail about the issue. It will give a warning about which bug type and its code location.

https://github.com/SonarQubeCommunity/sonar-findbugs/releases/tag/3.4 (sonar-findbugs-plugin-3.4.4-SNAPSHOT-alpha.jar)

Please copy the log output of the FindBugs plugin in this isse.

**Comment by mhankus** [comment]
Output is very long (but is looks almost the same). Right now it throws NPE even for ordinary classes (not jsp - sample below) (Class was generated during the build process by JPAMetaModelEntityProcessor)

```
09:31:27 [INFO] Loading findbugs plugin: /var/lib/jenkins/workspace/SiteReports/persistence/target/sonar/findbugs/findsecbugs-plugin.jar
09:31:27 [INFO] Findbugs output report: /var/lib/jenkins/workspace/SiteReports/persistence/target/sonar/findbugs-result.xml
09:31:51 [WARNING] An error occurs while processing the bug instance [BugInstance type=UUF_UNUSED_PUBLIC_OR_PROTECTED_FIELD, class=entities.AbstractDistlist_, line=-1]
09:31:51 java.lang.NullPointerException: null
09:31:51 	at org.sonar.plugins.findbugs.resource.SmapParser.<init>(SmapParser.java:98) ~[na:na]
09:31:51 	at org.sonar.plugins.findbugs.resource.ByteCodeResourceLocator.getJspLineNumberFromSmap(ByteCodeResourceLocator.java:181) ~[na:na]
09:31:51 	at org.sonar.plugins.findbugs.resource.ByteCodeResourceLocator.extractSmapLocation(ByteCodeResourceLocator.java:150) ~[na:na]
09:31:51 	at org.sonar.plugins.findbugs.FindbugsSensor.execute(FindbugsSensor.java:142) ~[na:na]
09:31:51 	at org.sonar.scanner.sensor.SensorWrapper.analyse(SensorWrapper.java:53) [sonar-scanner-engine-shaded-6.0.jar:na]
09:31:51 	at org.sonar.scanner.phases.SensorsExecutor.executeSensor(SensorsExecutor.java:57) [sonar-scanner-engine-shaded-6.0.jar:na]
09:31:51 	at org.sonar.scanner.phases.SensorsExecutor.execute(SensorsExecutor.java:49) [sonar-scanner-engine-shaded-6.0.jar:na]
09:31:51 	at org.sonar.scanner.phases.AbstractPhaseExecutor.execute(AbstractPhaseExecutor.java:78) [sonar-scanner-engine-shaded-6.0.jar:na]
09:31:51 	at org.sonar.scanner.scan.ModuleScanContainer.doAfterStart(ModuleScanContainer.java:184) [sonar-scanner-engine-shaded-6.0.jar:na]
09:31:51 	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:142) [sonar-scanner-engine-shaded-6.0.jar:na]
09:31:51 	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:127) [sonar-scanner-engine-shaded-6.0.jar:na]
09:31:51 	at org.sonar.scanner.scan.ProjectScanContainer.scan(ProjectScanContainer.java:241) [sonar-scanner-engine-shaded-6.0.jar:na]
09:31:51 	at org.sonar.scanner.scan.ProjectScanContainer.scanRecursively(ProjectScanContainer.java:236) [sonar-scanner-engine-shaded-6.0.jar:na]
09:31:51 	at org.sonar.scanner.scan.ProjectScanContainer.scanRecursively(ProjectScanContainer.java:234) [sonar-scanner-engine-shaded-6.0.jar:na]
09:31:51 	at org.sonar.scanner.scan.ProjectScanContainer.doAfterStart(ProjectScanContainer.java:226) [sonar-scanner-engine-shaded-6.0.jar:na]
09:31:51 	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:142) [sonar-scanner-engine-shaded-6.0.jar:na]
09:31:51 	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:127) [sonar-scanner-engine-shaded-6.0.jar:na]
09:31:51 	at org.sonar.scanner.task.ScanTask.execute(ScanTask.java:47) [sonar-scanner-engine-shaded-6.0.jar:na]
09:31:51 	at org.sonar.scanner.task.TaskContainer.doAfterStart(TaskContainer.java:86) [sonar-scanner-engine-shaded-6.0.jar:na]
09:31:51 	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:142) [sonar-scanner-engine-shaded-6.0.jar:na]
09:31:51 	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:127) [sonar-scanner-engine-shaded-6.0.jar:na]
09:31:51 	at org.sonar.scanner.bootstrap.GlobalContainer.executeTask(GlobalContainer.java:115) [sonar-scanner-engine-shaded-6.0.jar:na]
09:31:51 	at org.sonar.batch.bootstrapper.Batch.executeTask(Batch.java:118) [sonar-scanner-engine-shaded-6.0.jar:na]
09:31:51 	at org.sonarsource.scanner.api.internal.batch.BatchIsolatedLauncher.execute(BatchIsolatedLauncher.java:62) [sonar-scanner-api-batch5142423077678209318.jar:na]
09:31:51 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_77]
09:31:51 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_77]
09:31:51 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_77]
09:31:51 	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_77]
09:31:51 	at org.sonarsource.scanner.api.internal.IsolatedLauncherProxy.invoke(IsolatedLauncherProxy.java:60) [sonar-scanner-api-2.6.jar:na]
09:31:51 	at com.sun.proxy.$Proxy130.execute(Unknown Source) [na:na]
09:31:51 	at org.sonarsource.scanner.api.EmbeddedScanner.doExecute(EmbeddedScanner.java:240) [sonar-scanner-api-2.6.jar:na]
09:31:51 	at org.sonarsource.scanner.api.EmbeddedScanner.runAnalysis(EmbeddedScanner.java:151) [sonar-scanner-api-2.6.jar:na]
09:31:51 	at org.sonarsource.scanner.maven.bootstrap.ScannerBootstrapper.execute(ScannerBootstrapper.java:78) [sonar-maven-plugin-3.0.2.jar:na]
09:31:51 	at org.sonarsource.scanner.maven.SonarQubeMojo.execute(SonarQubeMojo.java:112) [sonar-maven-plugin-3.0.2.jar:na]
09:31:51 	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134) [maven-core-3.3.9.jar:3.3.9]
09:31:51 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207) [maven-core-3.3.9.jar:3.3.9]
09:31:51 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153) [maven-core-3.3.9.jar:3.3.9]
09:31:51 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145) [maven-core-3.3.9.jar:3.3.9]
09:31:51 	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116) [maven-core-3.3.9.jar:3.3.9]
09:31:51 	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80) [maven-core-3.3.9.jar:3.3.9]
09:31:51 	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51) [maven-core-3.3.9.jar:3.3.9]
09:31:51 	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128) [maven-core-3.3.9.jar:3.3.9]
09:31:51 	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307) [maven-core-3.3.9.jar:3.3.9]
09:31:51 	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193) [maven-core-3.3.9.jar:3.3.9]
09:31:51 	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106) [maven-core-3.3.9.jar:3.3.9]
09:31:51 	at org.jvnet.hudson.maven3.launcher.Maven32Launcher.main(Maven32Launcher.java:132) [maven32-interceptor-1.7.jar:na]
09:31:51 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_77]
09:31:51 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_77]
09:31:51 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_77]
09:31:51 	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_77]
09:31:51 	at org.codehaus.plexus.classworlds.launcher.Launcher.launchStandard(Launcher.java:330) [plexus-classworlds-2.5.2.jar:na]
09:31:51 	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:238) [plexus-classworlds-2.5.2.jar:na]
09:31:51 	at jenkins.maven3.agent.Maven32Main.launch(Maven32Main.java:186) [maven32-agent-1.7.jar:na]
09:31:51 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_77]
09:31:51 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_77]
09:31:51 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_77]
09:31:51 	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_77]
09:31:51 	at hudson.maven.Maven3Builder.call(Maven3Builder.java:136) [na:na]
09:31:51 	at hudson.maven.Maven3Builder.call(Maven3Builder.java:71) [na:na]
09:31:51 	at hudson.remoting.UserRequest.perform(UserRequest.java:153) [remoting-2.62.jar:na]
09:31:51 	at hudson.remoting.UserRequest.perform(UserRequest.java:50) [remoting-2.62.jar:na]
09:31:51 	at hudson.remoting.Request$2.run(Request.java:332) [remoting-2.62.jar:na]
09:31:51 	at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:68) [remoting-2.62.jar:na]
09:31:51 	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_77]
09:31:51 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_77]
09:31:51 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_77]
09:31:51 	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_77]
09:31:51 
```



for jsp pages NPE is different

```
09:35:41 [WARNING] An error occurs while processing the bug instance [BugInstance type=XSS_JSP_PRINT, class=jsp.WEB_002dINF.pages.attachmentPage_jsp, line=621]
09:35:41 java.lang.NullPointerException: null
09:35:41 	at org.sonar.plugins.findbugs.resource.SmapParser.getSmapLocation(SmapParser.java:168) ~[na:na]
09:35:41 	at org.sonar.plugins.findbugs.resource.ByteCodeResourceLocator.getJspLineNumberFromSmap(ByteCodeResourceLocator.java:182) ~[na:na]
09:35:41 	at org.sonar.plugins.findbugs.resource.ByteCodeResourceLocator.extractSmapLocation(ByteCodeResourceLocator.java:150) ~[na:na]
09:35:41 	at org.sonar.plugins.findbugs.FindbugsSensor.execute(FindbugsSensor.java:142) ~[na:na]
09:35:41 	at org.sonar.scanner.sensor.SensorWrapper.analyse(SensorWrapper.java:53) [sonar-scanner-engine-shaded-6.0.jar:na]
09:35:41 	at org.sonar.scanner.phases.SensorsExecutor.executeSensor(SensorsExecutor.java:57) [sonar-scanner-engine-shaded-6.0.jar:na]
09:35:41 	at org.sonar.scanner.phases.SensorsExecutor.execute(SensorsExecutor.java:49) [sonar-scanner-engine-shaded-6.0.jar:na]
09:35:41 	at org.sonar.scanner.phases.AbstractPhaseExecutor.execute(AbstractPhaseExecutor.java:78) [sonar-scanner-engine-shaded-6.0.jar:na]
09:35:41 	at org.sonar.scanner.scan.ModuleScanContainer.doAfterStart(ModuleScanContainer.java:184) [sonar-scanner-engine-shaded-6.0.jar:na]
09:35:41 	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:142) [sonar-scanner-engine-shaded-6.0.jar:na]
09:35:41 	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:127) [sonar-scanner-engine-shaded-6.0.jar:na]
09:35:41 	at org.sonar.scanner.scan.ProjectScanContainer.scan(ProjectScanContainer.java:241) [sonar-scanner-engine-shaded-6.0.jar:na]
09:35:41 	at org.sonar.scanner.scan.ProjectScanContainer.scanRecursively(ProjectScanContainer.java:236) [sonar-scanner-engine-shaded-6.0.jar:na]
09:35:41 	at org.sonar.scanner.scan.ProjectScanContainer.scanRecursively(ProjectScanContainer.java:234) [sonar-scanner-engine-shaded-6.0.jar:na]
09:35:41 	at org.sonar.scanner.scan.ProjectScanContainer.doAfterStart(ProjectScanContainer.java:226) [sonar-scanner-engine-shaded-6.0.jar:na]
09:35:41 	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:142) [sonar-scanner-engine-shaded-6.0.jar:na]
09:35:41 	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:127) [sonar-scanner-engine-shaded-6.0.jar:na]
09:35:41 	at org.sonar.scanner.task.ScanTask.execute(ScanTask.java:47) [sonar-scanner-engine-shaded-6.0.jar:na]
09:35:41 	at org.sonar.scanner.task.TaskContainer.doAfterStart(TaskContainer.java:86) [sonar-scanner-engine-shaded-6.0.jar:na]
09:35:41 	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:142) [sonar-scanner-engine-shaded-6.0.jar:na]
09:35:41 	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:127) [sonar-scanner-engine-shaded-6.0.jar:na]
09:35:41 	at org.sonar.scanner.bootstrap.GlobalContainer.executeTask(GlobalContainer.java:115) [sonar-scanner-engine-shaded-6.0.jar:na]
09:35:41 	at org.sonar.batch.bootstrapper.Batch.executeTask(Batch.java:118) [sonar-scanner-engine-shaded-6.0.jar:na]
09:35:41 	at org.sonarsource.scanner.api.internal.batch.BatchIsolatedLauncher.execute(BatchIsolatedLauncher.java:62) [sonar-scanner-api-batch5142423077678209318.jar:na]
09:35:41 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_77]
09:35:41 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_77]
09:35:41 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_77]
09:35:41 	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_77]
09:35:41 	at org.sonarsource.scanner.api.internal.IsolatedLauncherProxy.invoke(IsolatedLauncherProxy.java:60) [sonar-scanner-api-2.6.jar:na]
09:35:41 	at com.sun.proxy.$Proxy130.execute(Unknown Source) [na:na]
09:35:41 	at org.sonarsource.scanner.api.EmbeddedScanner.doExecute(EmbeddedScanner.java:240) [sonar-scanner-api-2.6.jar:na]
09:35:41 	at org.sonarsource.scanner.api.EmbeddedScanner.runAnalysis(EmbeddedScanner.java:151) [sonar-scanner-api-2.6.jar:na]
09:35:41 	at org.sonarsource.scanner.maven.bootstrap.ScannerBootstrapper.execute(ScannerBootstrapper.java:78) [sonar-maven-plugin-3.0.2.jar:na]
09:35:41 	at org.sonarsource.scanner.maven.SonarQubeMojo.execute(SonarQubeMojo.java:112) [sonar-maven-plugin-3.0.2.jar:na]
09:35:41 	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134) [maven-core-3.3.9.jar:3.3.9]
09:35:41 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207) [maven-core-3.3.9.jar:3.3.9]
09:35:41 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153) [maven-core-3.3.9.jar:3.3.9]
09:35:41 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145) [maven-core-3.3.9.jar:3.3.9]
09:35:41 	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116) [maven-core-3.3.9.jar:3.3.9]
09:35:41 	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80) [maven-core-3.3.9.jar:3.3.9]
09:35:41 	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51) [maven-core-3.3.9.jar:3.3.9]
09:35:41 	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128) [maven-core-3.3.9.jar:3.3.9]
09:35:41 	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307) [maven-core-3.3.9.jar:3.3.9]
09:35:41 	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193) [maven-core-3.3.9.jar:3.3.9]
09:35:41 	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106) [maven-core-3.3.9.jar:3.3.9]
09:35:41 	at org.jvnet.hudson.maven3.launcher.Maven32Launcher.main(Maven32Launcher.java:132) [maven32-interceptor-1.7.jar:na]
09:35:41 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_77]
09:35:41 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_77]
09:35:41 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_77]
09:35:41 	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_77]
09:35:41 	at org.codehaus.plexus.classworlds.launcher.Launcher.launchStandard(Launcher.java:330) [plexus-classworlds-2.5.2.jar:na]
09:35:41 	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:238) [plexus-classworlds-2.5.2.jar:na]
09:35:41 	at jenkins.maven3.agent.Maven32Main.launch(Maven32Main.java:186) [maven32-agent-1.7.jar:na]
09:35:41 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_77]
09:35:41 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_77]
09:35:41 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_77]
09:35:41 	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_77]
09:35:41 	at hudson.maven.Maven3Builder.call(Maven3Builder.java:136) [na:na]
09:35:41 	at hudson.maven.Maven3Builder.call(Maven3Builder.java:71) [na:na]
09:35:41 	at hudson.remoting.UserRequest.perform(UserRequest.java:153) [remoting-2.62.jar:na]
09:35:41 	at hudson.remoting.UserRequest.perform(UserRequest.java:50) [remoting-2.62.jar:na]
09:35:41 	at hudson.remoting.Request$2.run(Request.java:332) [remoting-2.62.jar:na]
09:35:41 	at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:68) [remoting-2.62.jar:na]
09:35:41 	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_77]
09:35:41 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_77]
09:35:41 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_77]
09:35:41 	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_77]
```
I'm on vacation right now with limited access to computer, so my answers may be delayed.

**Comment by h3xstream** [comment]
@mhankus The mapping is done different in the latest release.

**Comment by h3xstream** [comment]
Bytecode file required to reproduce.
