### ISSUE TITLE
Findbugs-Plugin 3.4.3 run in Timeout

### ISSUE THREAD

**Issue by BlackAngelTiger** [SonarQubeCommunity/sonar-findbugs#50]
We are using the Java-Plug-In 4.0 and 4.1 with the Findbugs Plug-In 3.4.3 and the Find Bugs analysis doesn't end. There could be a endless loop some where or the provided date which are 13.269 class files 
with the size of 249 MB as binaries and 239 Jars with 251 MB for libraries are to big to handle for the new Findbugs Plug-In.

As you can see in the different Pictures, the java process is using memory and CPU over time and gets higher and higher. But the findbugs-result.xml part doesn't finish in time and run in a Timeout.

With the Java-Plugin Version 3.14 and Findbugs 3.3 this works fine.

This error could be unnoticed if you have only smaller projects with less binaries and libraries which have to be analyzed.

We also tried if this is a problem with one of the rules but this problem still happens if we only have one rule active and we also changed the rule to be sure that this is not a problem of one rule.

Best Regards

**Comment by h3xstream** [comment]
Please provide the error message or stacktrace.

**Comment by BlackAngelTiger** [comment]
Sorry the pictures doesn't got added.

![cmd-scanner-error-findbugs](https://cloud.githubusercontent.com/assets/6084676/17998763/4c42bd58-6b76-11e6-9b98-fc0191dc8858.PNG)
![sonarqube-execution-java-ressources-1](https://cloud.githubusercontent.com/assets/6084676/17998767/4c476cd6-6b76-11e6-9b96-c76eaedae70a.PNG)
![sonarqube-execution-java-ressources-4](https://cloud.githubusercontent.com/assets/6084676/17998765/4c44e7b8-6b76-11e6-995f-a41d35dcba1b.PNG)

**Comment by BlackAngelTiger** [comment]
The error Message is:
`
ERROR: Error during SonarQube Scanner execution
java.lang.IllegalStateException: Can not execute Findbugs with a timeout threshold value of 600000 milliseconds
        at org.sonar.plugins.findbugs.FindbugsExecutor.execute(FindbugsExecutor.java:167)
        at org.sonar.plugins.findbugs.FindbugsSensor.execute(FindbugsSensor.java:88)
        at org.sonar.batch.sensor.SensorWrapper.analyse(SensorWrapper.java:57)
        at org.sonar.batch.phases.SensorsExecutor.executeSensor(SensorsExecutor.java:58)
        at org.sonar.batch.phases.SensorsExecutor.execute(SensorsExecutor.java:50)
        at org.sonar.batch.phases.AbstractPhaseExecutor.execute(AbstractPhaseExecutor.java:83)
        at org.sonar.batch.scan.ModuleScanContainer.doAfterStart(ModuleScanContainer.java:192)
        at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:142)
        at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:127)
        at org.sonar.batch.scan.ProjectScanContainer.scan(ProjectScanContainer.java:241)
        at org.sonar.batch.scan.ProjectScanContainer.scanRecursively(ProjectScanContainer.java:236)
        at org.sonar.batch.scan.ProjectScanContainer.doAfterStart(ProjectScanContainer.java:226)
        at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:142)
        at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:127)
        at org.sonar.batch.task.ScanTask.execute(ScanTask.java:47)
        at org.sonar.batch.task.TaskContainer.doAfterStart(TaskContainer.java:86)
        at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:142)
        at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:127)
        at org.sonar.batch.bootstrap.GlobalContainer.executeTask(GlobalContainer.java:106)
        at org.sonar.batch.bootstrapper.Batch.executeTask(Batch.java:119)
        at org.sonarsource.scanner.api.internal.batch.BatchIsolatedLauncher.execute(BatchIsolatedLauncher.java:62)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.sonarsource.scanner.api.internal.IsolatedLauncherProxy.invoke(IsolatedLauncherProxy.java:60)
        at com.sun.proxy.$Proxy0.execute(Unknown Source)
        at org.sonarsource.scanner.api.EmbeddedScanner.doExecute(EmbeddedScanner.java:240)
        at org.sonarsource.scanner.api.EmbeddedScanner.runAnalysis(EmbeddedScanner.java:151)
        at org.sonarsource.scanner.cli.Main.runAnalysis(Main.java:110)
        at org.sonarsource.scanner.cli.Main.execute(Main.java:72)
        at org.sonarsource.scanner.cli.Main.main(Main.java:60)
Caused by: java.util.concurrent.TimeoutException
        at java.util.concurrent.FutureTask.get(FutureTask.java:205)
        at org.sonar.plugins.findbugs.FindbugsExecutor.execute(FindbugsExecutor.java:163)
        ... 31 more
`

**Comment by h3xstream** [comment]
You can increase the threshold from the administration section of the project.
You can replace the default value with **3600000** (1 hour).

![timeout](https://cloud.githubusercontent.com/assets/593130/18062397/b0db6f00-6df4-11e6-8827-480b3e0ee1ad.png)

Let me know if the build succeed after..

**Comment by h3xstream** [comment]
Quick Note on profiling the Maven build. You can attach [VisualVM](https://visualvm.java.net/) to your Maven build.

**Comment by BlackAngelTiger** [comment]
Ok, that seems to work. But this is quiet hard. I don't use maven I am using ant at the moment. This will be object to change in the near future.

**Comment by BlackAngelTiger** [comment]
But the Performance Gabe between Version 3.3 and 3.4.3 is from a average time of 2 min per project to 20 min per project. 

Used the versions FB 3.4 with Java 3.14 and FB 3.4.3 with Java 4.2.

**Comment by BrunoLavitForgerock** [comment]
@h3xstream Thanks for your help, it solved my issue ;-)

**Comment by vladkras** [comment]
It's not a solution, but I just uninstalled FindBugs plugin in my SonarQube Marketplace to finish the analysis, cause my findbugs-result.xml never got bigger then 0 bytes.
